config/routes.rb
Rails.application.routes.draw do
  root "search_results#new"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips do
    resources :messages
  end

  resources :users do
    resources :messages
  end

  resources :users
  get '/user_searches' => 'search_results#user_index'

  get '/search_results' =>  'search_results#index'
  post '/search_results' => 'search_results#create'
  get '/save_search' =>  'search_results#new'
  post '/save_search' => 'search_results#save_result'

  get '/guides/search' => "guides#find_guides"
  resources :guides, only: [:index, :new]

  resources :search_results do
    get :autocomplete_location_city, :on => :collection
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :origin, class_name: "Location"
  belongs_to :destination, class_name: "Location"
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  has_many :travelers
  has_many :confirmed_travelers, through: :travelers, source: :user

  has_many :messages, as: :messageable

  validates :origin, presence: true
  validates :destination, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :user_id, presence: true
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :update, :destroy, :edit]

  def index
    if current_user
      @created_trips = current_user.created_trips
      @joined_trips = current_user.trips
    else
      @trips = Trip.order(:start_at).limit(25)
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id

    if @trip.save
      redirect_to  @trip
    else
      redirect_to '/'
    end
  end

  def show
    #For Mapbox
    @coord = [[@trip.destination.lat, @trip.destination.lng],
              [@trip.origin.lat, @trip.origin.lng]]

    respond_to do |format|
      format.html
      format.json { render json: @coord }
    end
  end

  private
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:origin_id, :destination_id, :start_at, :end_at)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
  <%= f.hidden_field :origin, value: result.origin %>
  <%= f.hidden_field :destination, value: result.destination %>
  <%= f.hidden_field :start_at, value: result.depart_time%>
  <%= f.hidden_field :end_at, value: result.return_time%>
  <%= f.hidden_field :user, value: current_user %>

  <%= f.submit "Save Trip" %>
<% end %>

app/views/trips/index.html.erb
<div class="standard_box">
  <% if @created_trips.count != 0 %>
    <h1> Your Created Trips </h1>
    <% @created_trips.each do |trip| %>
      <div class="trips_list">
        <h3><%= link_to trip.destination.city.capitalize, trip_path(id: trip.id) %><h3>
        <h4>From <%= trip.start_at %> to <%= trip.end_at %></h4>
      </div>
    <% end %>
  <% end %>

  <% if @joined_trips.count != 0 %>
    <h1> Trips You've Joined </h1>
    <% @joined_trips.each do |trip| %>
      <div class="trips_list">
        <h3><%= link_to trip.destination.city.capitalize, trip_path(id: trip.id) %><h3>
        <h4>From <%= trip.start_at %> to <%= trip.end_at %></h4>
      </div>
    <% end %>
  <%end%>
</div>
<div id="background"></div>

app/views/trips/show.html.erb
<div id="fb-root"></div>
<div id="tripmap"></div>


<script type="text/javascript" id="coords">
  window.coords = <%= @coord.to_json %>;
</script>
<div class="content">
    <!--- insert link to trip on momondo -->
    <% if current_user %>
      <%= button_to "Book it!", nil, {class: "book"} %>
    <% else %>
      <%= button_to "Book it!", nil, {class: "book"} %>
      <%= button_to "Join", nil, {class: "join-trip"} %>
    <% end %>

    <h1 class="content-header">Join my Trip!</h1>
    <div id="trip_creator"><h1><%= link_to @trip.creator.username.capitalize, user_path(@trip.creator.id) %></h1></div>

    <div id="information">
      <div class="info">
        <h1>From <%=@trip.origin.city.capitalize %> to <%=@trip.destination.city.capitalize %> </h1>
         <!--  <%= form_for @trip do |f| %>
            <%= f.text_area :description, class: 'description', :rows => 5 %>
          <% end %> -->
        <div id="social_media">
          <h1 id="invite">Invite Friends:</h1>
          <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-width="24px" data-layout="button"></div>
          <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-text="Join my trip to <%= @trip.destination.city.capitalize %>!">Tweet
          </a>
        </div>
      </div>
      <div id="sug_guides">
        <h1>Suggested Guides</h1>

        <div id="each_guide">
          <% @trip.destination.guides[0..2].each_with_index do |guide| %>
            <%= link_to guide.first_name.capitalize, user_path(guide.id), class: "user-link" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>