config/routes.rb
Rails.application.routes.draw do
  root "search_results#new"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips do
    resources :messages
  end

  resources :users do
    resources :messages
  end

  resources :users
  get '/user_searches' => 'search_results#user_index'

  get '/search_results' =>  'search_results#index'
  post '/search_results' => 'search_results#create'
  get '/save_search' =>  'search_results#new'
  post '/save_search' => 'search_results#save_result'

  get '/guides/search' => "guides#find_guides"
  resources :guides, only: [:index, :new]

  resources :search_results do
    get :autocomplete_location_city, :on => :collection
  end

end

app/models/search_result.rb
class SearchResult < ActiveRecord::Base
  belongs_to :user
  has_many :search_result_locations
  has_many :locations, through: :search_result_locations

  validates :budget, presence: true
  validates :start_at, presence: true
end

app/controllers/search_results_controller.rb
require 'momondo/client.rb'

class SearchResultsController < ApplicationController
  before_action :set_user_results, only: [:user_index]
  before_action :set_result, only: [:show]

  def autocomplete_location_city
    cities = Location.where("city ILIKE ?", "%#{params[:term]}%").pluck(:city)
    render :json => cities
  end

  def index
  end

  def new
    @guides = User.where(guide: true)

    @search_result = SearchResult.new
    @ip = request.ip
    @user_location = Location.new
    @city = @user_location.geo_locate(@ip)
  end

  def create
    @guides = User.where(guide: true)
    @search_result = SearchResult.new(search_result_params)
    @client = Momondo::Client.new
    @city_search = Location.where(city: params[:search_result][:current_city])

    if @search_result.current_city.empty? || @city_search.empty?
      flash[:error] = "Invalid City"
      render "search_results/new"
      return
    elsif @search_result.budget.nil?
      flash[:error] = "Invalid"
      render "search_results/new"
      return
    else
      airport_code = convert_city_to_airport(@search_result.current_city.downcase)
      @results = @client.where_to_go(leave_date: @search_result.start_at.to_s ,leave_from: airport_code, max_price: @search_result.budget)
    end

    if current_user
      @search_result.user_id = current_user.id
    end

    if @search_result.save
      @results.each do |result|
        @converted_location_city = convert_airport_to_city(result.destination)
        @location = Location.find_by(city: @converted_location_city)
        @search_location = SearchResultLocation.new(location_id: @location.id, search_result_id: @search_result.id)
        @search_location.save
      end
      render "search_results/index"
    # else
    #   redirect_to '/'
    end
  end

  def save_result
    @search = SearchResult.find(params[:search])
    @search.visible = true

    if @search.save
      redirect_to 'search_results/#{@search.id}'
    else
      render '/'
    end
  end

  private
  def set_user_results
    @results = current_user.search_results
  end

  def set_result
    @result = SearchResult.find(params[:id])
  end

  def search_result_params
   params.require(:search_result).permit(:current_city, :budget, :start_at, :end_at)
 end

  def convert_city_to_airport(current_city)#this method convert the city into airport code
   Location.find_by(city: current_city).airports.first.code
 end

 def convert_airport_to_city(code)
  if code != nil
    @destination = Airport.find_by(code: code).location.city
  end
end
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
  def convert_airport_to_city(code)
    if code != nil
    @destination = Airport.find_by(code: code).location.city
    end
  end

  def make_url(result)
    url = "blah"
  end

  def momondo_url(result)
    query = URI.encode_www_form({
                                  :"Search" => true,
                                  :"TripType" => "return",
                                  :"SegNo" => 2,
                                  :"SO0" => result.origin,
                                  :"SD0" => result.destination,
                                  :"SDP0" => result.depart_time,
                                  :"SO1" => result.destination,
                                  :"SD1" => result.origin,
                                  :"SDP1" => result.return_time,
                                  :"AD" => 1,
                                  :"rt" => true,
                                  :"Search" => true,
                                  :TripType => "return",
                                  :SegNo => 2,
                                  :SO0 => result.origin,
                                  :SD0 => result.destination,
                                  :SDP0 => result.depart_time,
                                  :SO1 => result.destination,
                                  :SD1 => result.origin,
                                  :SDP1 => result.return_time,
                                  :AD => 1,
                                  :TK => "ECO",
                                  :DO => false,
                                  :NA => false
                                })
    "http://www.momondo.com/multicity/?#{query}"
  end
end

app/views/search_results/_form.html.erb
<%= form_for @search_result, html: {id: "flight-search"} do |f| %>
  <div id="city-field">
    <%= f.label "I want to get out of" %>
    <%= f.text_field :current_city, value: @city, include_blank: true, :"data-autocomplete-path" => autocomplete_location_city_search_results_path %><br>
  </div>
  <div id="date-field">
    <%= f.label "by" %>
    <%= f.date_select :start_at, start_year: 2015, discard_day: true, order: [:month, :year]  %><br>
  </div>

  <div id="budget-field">
    <%= f.label "with     $" %>
    <%= f.text_field :budget  %><br>
  </div>

  <div id="submit">
  <%= f.submit "Send me Away!" %><br><br>
  </div>
    <%= flash[:error] %>
<% end %>

app/views/search_results/index.html.erb
<!-- SIDE BAR: SHOWS ALL POTENTIAL DESTINATIONS-->
  <!-- DONE! -->
  <h3 id="destinations"> Choose Your <br> Destination: </h3>
  <div id="result-list">
    <ul>
      <% @results.each do |result| %>
        <li> <%= link_to convert_airport_to_city(result.destination).capitalize, anchor: result.destination %> </li>
      <% end %>
    </ul>
  </div>

<!-- LISTS ALL DESTINATION W/ INFO -->

<div class="wrapper">
  <% @results.each do |result| %>
    <!-- DIV FOR SIDE MENU LINKS-->

    <div class="result-card">
      <h1 class="title"><%= convert_airport_to_city(result.destination).capitalize %></h1>
      <h3 class="budget">$<%= GoogCurrency.eur_to_usd(result.price).to_i%></h3>

      <p>Leave <%= convert_airport_to_city(result.origin).capitalize %>
        <%= result.depart_time.month %>/<%= result.depart_time.day %>/<%= result.depart_time.year %>
        <br>
        Leave  <%= convert_airport_to_city(result.destination).capitalize %>
        <%= result.return_time.month %>/<%= result.return_time.day %>
        /<%= result.return_time.year %>
        <br><br>
      <% @guides = Location.find_by(city: convert_airport_to_city(result.destination)).guides %>
      <% if @guides.count > 0 %>
        <%= @guides.count %> Guides Available
      <% else %>
         No Guides Available in this Location
      <%end%>
      </p><br>

      <%= form_for Trip.new do |f| %>
        <%= f.hidden_field :origin_id, value: Location.find_by(city: convert_airport_to_city(result.origin)).id %>
        <%= f.hidden_field :destination_id, value: Location.find_by(city: convert_airport_to_city(result.destination)).id %>
        <%= f.hidden_field :start_at, value: result.depart_time%>
        <%= f.hidden_field :end_at, value: result.return_time%>

        <%= f.submit "Save Trip" %>
      <% end %>

      <span class="button "><%= link_to "Book Ticket", momondo_url(result), :target => "_blank" %></span>

      <div id="<%=result.destination%>"></div>
    </div>
  <% end %>
</div>

app/views/search_results/new.html.erb
<div id="map"></div>
<div id="loginAjax"></div>
<div class="header">
  <h1>Raft</h1>
  <div class="sub-heading">
    <% if current_user %>
      <h2> Hello <%= current_user.first_name %>!</h2>
    <% else %>
      <h2>  taking you around the world   </h2>
      <h2> with <%= @guides.count %> guides & counting </h3>
    <% end %>
  </div>
</div>

<div class="search-box">
  <h1 id="box-head">Find your Destination...</h1>
  <%= render "search_results/form" %>
</div>

app/views/search_results/show.html.erb
<%= @result.current_city %>
<%= @result.budget %>
<div id="background"></div>

app/views/search_results/user_index.html.erb
<div class="standard_box">
  <% if @results.count != 0 %>
    <h1> Your Previous Searches </h1>
    <% @results.each do |result| %>
      $<%= result.budget %>
      From: <%= result.start_at %>
      <% result.locations.each do |location| %>
        <%= location.city %>
        <% end %>
      <br><br>
    <% end %>
  <% else %>
    <h2> You have no Searches! </h2>
  <%end%>
</div>
<div id="background"></div>