config/routes.rb
Rails.application.routes.draw do
  root "search_results#new"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips do
    resources :messages
  end

  resources :users do
    resources :messages
  end

  resources :users
  get '/user_searches' => 'search_results#user_index'

  get '/search_results' =>  'search_results#index'
  post '/search_results' => 'search_results#create'
  get '/save_search' =>  'search_results#new'
  post '/save_search' => 'search_results#save_result'

  get '/guides/search' => "guides#find_guides"
  resources :guides, only: [:index, :new]

  resources :search_results do
    get :autocomplete_location_city, :on => :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :location

  has_many :travelers
  has_many :trips, through: :travelers

  has_many :created_trips, class_name: "Trip", source: :creator

  has_many :destinations, through: :trips
  has_many :origins, through: :trips

  has_many :search_results
  has_many :search_result_locations, through: :search_results
  has_many :searched_locations, through: :search_result_locations, source: :location

  has_many :created_messages, class_name: "Message", foreign_key: :creator_id
  has_many :messages, as: :messageable

  validates :username, uniqueness: true, presence: true
  # validates :email, uniqueness: true, presence: true
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_length_of :bio,
    :maximum => 2000,
    :too_long => "You are limited to 2000 characters"

  # mount_uploader :avatar, AvatarUploader
  has_secure_password
end

app/controllers/users_controller.rb
require 'location.rb'

class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @locations = Array.new

    @user.created_trips.each do |trip|
      @locations << trip.destination
    end

    @user.trips.each do |trip|
      @locations << trip.destination
    end
  end

  def create
    @user= User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "You created an account"
    else
      @error = "Sign up failed: Try again."
      render :new
    end
  end

  def update
    @guide = User.find(session[:user_id])
    @location = Location.find_by(city: (params[:user][:location]).downcase)

    if @location
      @guide.update(params_guide.merge(location: @location))
      lat = @location.latitude(@location.city)
      lng = @location.longitude(@location.city)
      @location.update(lat: lat, lng: lng)

      redirect_to @guide
    else
      render 'guides/new'
    end

    end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :age, :email, :bio, :guide, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def params_guide
    params.require(:user).permit(:guide)
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :age %>
  <%= f.text_field :age, :placeholder =>"Optional" %>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password, "confirmed your password" %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<%end%>

app/views/users/index.html.erb
<div class="standard_box">
  <% @users.each do |user| %>
  <%= link_to user.first_name, user_path(user.id) %>
  <% end %>
</div>
<div id="background"></div>

app/views/users/new.html.erb
<div class="standard_box">
  <h1> Welcome create an account </h1>
  <%= @error if @error %>
  <%= render 'form' %>
</div>
<div id="background"></div>

app/views/users/show.html.erb
<div class="user_box">
  <div class = "button_links_user">
    <% if @user.id == current_user.id %>
      <%= link_to "Read your Messages", user_messages_path(@user.id), :id => 'write_message' %>
    <% else %>
      <%= link_to "Message this person!", new_user_message_path(@user.id) , :id => 'write_message' %>
    <% end %><br>
  </div>

  <div id="picture_holder">
    <img class = "user_picture" src="http://traveler.lodossteam.com/content/images/2014/Mar/1.jpg">
  </div>

  <div id="first_name">
    <h1><%= @user.first_name %> <%= @user.last_name %></h1>
    <p><%= @user.bio %></p>
  </div>

  <div id='guide_status'>
    <% if @user.guide == true %>
    <h2 id="guide_status"><%= "I am available to guide you through the streets of #{@user.location.city.capitalize}" %></h2>
    <% end %>
  </div>
</div>
</div>
<div id= "jsform"></div>