config/routes.rb
Rails.application.routes.draw do
  root "search_results#new"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips do
    resources :messages
  end

  resources :users do
    resources :messages
  end

  resources :users
  get '/user_searches' => 'search_results#user_index'

  get '/search_results' =>  'search_results#index'
  post '/search_results' => 'search_results#create'
  get '/save_search' =>  'search_results#new'
  post '/save_search' => 'search_results#save_result'

  get '/guides/search' => "guides#find_guides"
  resources :guides, only: [:index, :new]

  resources :search_results do
    get :autocomplete_location_city, :on => :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raft</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.css' rel='stylesheet' />
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

<body>
  <div id="top">
    <header>
      <nav>
      <h2><%= link_to 'Raft', '/' %></h2>
      <ul>
        <% if current_user%>
          <li ><%= link_to current_user.username.capitalize, user_path(current_user.id) %></li>
          <li ><%= link_to 'Trips', trips_path %></li>
          <li><%= link_to 'Guides', guides_path %></li>
          <li><%= link_to 'Sign Out', '/logout' %></li>
        <% else %>
          <li><%= link_to 'Log In', '/login', :id => 'login' %></li>
          <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
      </ul>
    </nav>
    </header>
  </div>

  <%= yield %>

  <footer>
  </footer>
</body>
</html>